[package]
name = "raft"
version = "0.4.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["raft", "distributed-systems", "ha"]
repository = "https://github.com/pingcap/raft-rs"
readme = "README.md"
homepage = "https://github.com/pingcap/raft-rs"
documentation = "https://docs.rs/raft"
description = "The rust language implementation of Raft algorithm."
categories = ["algorithms", "database-implementations"]

[features]
default = ["harness"]
# Enable failpoints
failpoint = ["fail"]
# Enable the testing harness.
# This is required to run `cargo test` or `cargo bench`.
harness = ["env_logger"]

[dependencies]
log = ">0.2"
protobuf = "2.0.4"
quick-error = "1.2.2"
rand = "0.5.4"
fxhash = "0.2.1"
# Rust does not offer a common feature flag for tests and benches.
# So we have these optional behind features.
fail = { version = "0.2", optional = true }
env_logger = { version = "0.5", optional = true }

[dev-dependencies]
criterion = ">0.2.4"
lazy_static = "1.0"

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "pingcap/raft-rs" }

[[example]]
name = "single_mem_node"
path = "examples/single_mem_node/main.rs"
